'use strict';

/**
 * report.js
 *
 * Generates a single self-contained HTML report page for the 2026 World Cup:
 * title odds table, expected group stage standings, team path probabilities, and
 * a short model note. The report is dependency-free (all CSS is inline).
 */

const { GROUPS, GROUP_OF } = require('./worldcup2026');
const { predictMatch, HOSTS } = require('./simulation');

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function pct(p) {
  return (p * 100).toFixed(1) + '%';
}

function num(n, digits = 2) {
  return Number(n).toFixed(digits);
}

function computeExpectedStandings(elo, groupTeams, rho) {
  const table = {};
  for (const t of groupTeams) {
    table[t] = { team: t, pts: 0, xg: 0, xga: 0, xgd: 0 };
  }
  for (let i = 0; i < groupTeams.length; i++) {
    for (let j = i + 1; j < groupTeams.length; j++) {
      const A = groupTeams[i];
      const B = groupTeams[j];
      const r = predictMatch(elo.getRating(A), elo.getRating(B), HOSTS.has(A), HOSTS.has(B), rho);
      table[A].pts += 3 * r.pWin + 1 * r.pDraw;
      table[B].pts += 3 * r.pLoss + 1 * r.pDraw;
      table[A].xg += r.xgA;
      table[A].xga += r.xgB;
      table[B].xg += r.xgB;
      table[B].xga += r.xgA;
    }
  }
  for (const t of groupTeams) {
    table[t].xgd = table[t].xg - table[t].xga;
  }
  return Object.values(table).sort((a, b) => b.pts - a.pts || b.xgd - a.xgd || b.xg - a.xg);
}

function titleOddsRows(odds) {
  const rows = Object.entries(odds).sort((a, b) => b[1].champion - a[1].champion);
  return rows
    .map(([team, p], i) => {
      return `        <tr><td>${i + 1}</td><td>${escapeHtml(team)}</td><td>${GROUP_OF[team]}</td><td>${pct(p.champion)}</td><td>${pct(p.final)}</td><td>${pct(p.sf)}</td><td>${pct(p.qf)}</td><td>${pct(p.r16)}</td><td>${pct(p.r32)}</td></tr>`;
    })
    .join('\n');
}

function groupStandingsRows(standings) {
  return standings
    .map((t, i) => {
      return `        <tr><td>${i + 1}</td><td>${escapeHtml(t.team)}</td><td>${num(t.pts, 1)}</td><td>${num(t.xg, 2)}</td><td>${num(t.xga, 2)}</td><td>${num(t.xgd, 2)}</td></tr>`;
    })
    .join('\n');
}

function groupTables(elo, rho) {
  return Object.entries(GROUPS)
    .map(([letter, teams]) => {
      const standings = computeExpectedStandings(elo, teams, rho);
      const rows = groupStandingsRows(standings);
      return `
      <div class="group-table">
        <h4>Group ${letter}</h4>
        <table>
          <thead><tr><th>Pos</th><th>Team</th><th>Exp Pts</th><th>xG</th><th>xGA</th><th>xGD</th></tr></thead>
          <tbody>
${rows}
          </tbody>
        </table>
      </div>`;
    })
    .join('\n');
}

function pathRows(odds) {
  const rows = Object.entries(odds).sort((a, b) => b[1].champion - a[1].champion);
  return rows
    .map(([team, p]) => {
      return `        <tr><td>${escapeHtml(team)}</td><td>${GROUP_OF[team]}</td><td>${pct(p.champion)}</td><td>${pct(p.final)}</td><td>${pct(p.sf)}</td><td>${pct(p.qf)}</td><td>${pct(p.r16)}</td><td>${pct(p.r32)}</td></tr>`;
    })
    .join('\n');
}

function generateReportHTML({ odds, elo, rho, modelText = '' } = {}) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Polycup — 2026 World Cup Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 24px; background: #f4f6f8; color: #212529; }
  .container { max-width: 1100px; margin: 0 auto; background: #fff; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); padding: 28px; }
  h1 { margin: 0 0 6px; font-size: 26px; }
  h2 { margin-top: 28px; font-size: 20px; border-bottom: 1px solid #dee2e6; padding-bottom: 8px; }
  .subtitle { color: #6c757d; margin-bottom: 18px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 18px; }
  .group-table { background: #f8f9fa; border-radius: 6px; padding: 12px; }
  .group-table h4 { margin: 0 0 8px; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #dee2e6; }
  th { background: #f8f9fa; font-weight: 600; text-transform: uppercase; font-size: 11px; }
  tr:last-child td { border-bottom: none; }
  .scroll { overflow-x: auto; }
  .note { margin-top: 28px; font-size: 13px; color: #6c757d; border-top: 1px solid #dee2e6; padding-top: 14px; }
  @media (max-width: 600px) { .grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<div class="container">
  <h1>Polycup — 2026 FIFA World Cup Report</h1>
  <div class="subtitle">Generated by the Elo + Dixon-Coles + Monte Carlo model ${modelText}</div>

  <h2>Title odds</h2>
  <div class="scroll">
    <table>
      <thead>
        <tr><th>Rank</th><th>Team</th><th>Group</th><th>Champion</th><th>Final</th><th>Semis</th><th>Quarters</th><th>Round of 16</th><th>Round of 32</th></tr>
      </thead>
      <tbody>
${titleOddsRows(odds)}
      </tbody>
    </table>
  </div>

  <h2>Expected group stage standings</h2>
  <p class="subtitle">Expected points, expected goals, and expected goal difference are computed analytically from the Dixon-Coles match probabilities (not a single random simulation).</p>
  <div class="grid">
${groupTables(elo, rho)}
  </div>

  <h2>Team path probabilities</h2>
  <div class="scroll">
    <table>
      <thead>
        <tr><th>Team</th><th>Group</th><th>Champion</th><th>Final</th><th>Semis</th><th>Quarters</th><th>Round of 16</th><th>Round of 32</th></tr>
      </thead>
      <tbody>
${pathRows(odds)}
      </tbody>
    </table>
  </div>

  <div class="note">
    <strong>About the model:</strong> Polycup is a zero-dependency Node.js CLI. It builds Elo ratings from ~49,000 historical international matches, estimates a Dixon-Coles &rho; from the same data, and runs a Monte Carlo simulation of the official FIFA 2026 48-team tournament (12 groups + 8 best third-place teams + fixed-seeding knockout bracket). The model is for entertainment only and is <strong>not betting advice</strong>.
  </div>
</div>
</body>
</html>
`;

  return html;
}

module.exports = { generateReportHTML, computeExpectedStandings };
